= TODO

This repository is a place for me to experiment with different languages accross
computers. I plan on creating a todo application here one day but for now it is
just a playing ground.

== TODO

=== Requirements

. List tasks by priority, and by date inside priorities.
. Git version control.
. Save completed tasks but don't list them anymore.
. Reopen completed tasks.
. List completed tasks.
. Edit task.
    * Change priority
    * Change subject
    * Change content
. Task
. creation and update date.

=== Ruby script

This is the help text for the ruby script. I was using binman to try generate
the help a la perl's pod but got tired of it. I will write this (when it is
done) in asciidoc and generate a proper man page for it.

[verbating]
----
## NAME

todo - keep track of your day!

## SYNOPSIS

`todo` [--help] [--version] [*COMMAND*] [*OPTIONS*]

## COMMANDS

`list` [-t|--track] [-f|--filename] [-c|--closed]
  Show a list of todo's (default) or a list of day tracks.

  Note: The index given by this command can be used everywhere else.

  `--track` Show index for tracks.

  `--filename` Show filename for todo's instead of subject.

  `--closed` Show closed todo's.

`create` *SUBJECT* [-e|--edit] [-p|--priority *PRIORITY*]
  Create a todo. Use --edit to launch an editor after creation.

`time` *SUBJECT*
  Track a new activity in your day track.

`track` [*INDEX*]
  Show the given day's (defaults to current) tracked activities.

`edit` *INDEX* [-t|--track] [-c|--closed]
  Edit a todo (default) or a day track.

  `--track` Edit tracks.

  `--closed` Edit closed todo's.

`close` *INDEX*
  Close a todo.

`reopen` *INDEX*
  Reopen a todo.

`rm` *INDEX* [-t|--track] [-c|--closed]
  Delete a todo (default) or a day track.

  `--track` Delete tracks.

  `--closed` Delete closed todo's.

## BUG REPORTS

https://github.com/DavidGamba/todo.git
----

=== Play application

I want to do a play application with a rest API so the cmdline script can just
call the play application, in that way I have both interfaces, and nice gui and
a nice cmdline script.

I will experiment with the application so the code might not be entirely related
to a todo list.
